DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8
IgnoreServerErrors: []
DisableStartupLog: false
DisableInterruptHandler: false
DisableVersionChecker: false
EnableOptimizations: false
DisableAutoFireStatusCode: false
TranslateFunctionContextKey: iris.translate
TranslateLanguageContextKey: iris.language
ViewLayoutContextKey: iris.viewLayout
ViewDataContextKey: iris.viewData
RemoteAddrHeaders:
  CF-Connecting-IP: false
  X-Forwarded-For: false
  X-Real-Ip: false
Other: {}